os:
- linux
- osx
# - windows # java not yet supported on windows

cache:
  directories:
  - $HOME/.m2

language: java

addons:
  apt:
    packages:
    - oracle-java8-installer

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: openjdk8
  - os: osx

#osx_image: xcode9.3

before_install:

install:
- mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
- echo "TRAVIS_OS_NAME = ${TRAVIS_OS_NAME}"
- mvn package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true