cache:
  directories:
  - $HOME/.m2

language: java

#addons:
#  apt:
#    packages:
#    - oracle-java8-installer

#matrix:
#  include:
#  - os: linux
#    jdk: oraclejdk8
#  - os: linux
#    jdk: openjdk8
#  - os: osx

# matrix:
#   include:
#   - os: linux
#     jdk: oraclejdk8
#   - os: osx
#     jdk: oraclejdk8
#     osx_image: xcode9.3

matrix:
  include:
  - os: linux
    language: java
    addons:
      apt:
        packages:
        - oracle-java8-installer
    install:
    - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
    script:
    - mvn test && mvn verify
  - os: osx
    jdk: oraclejdk8
    osx_image: xcode9.3
    install:
    - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
    script:
    - mvn test && mvn verify


  - #jobs:
    #  include:
    #  - stage: Unit Tests
    #    script: echo "Running Unit Tests"
    #    os:
    #    - linux
    #    - osx
    #  - stage: Integration Tests
    #    script: echo "Running Integration Tests"
    #    os:
    #    - linux
    #    - osx
    #  - stage: Deploy
    #    script: echo "Running deploy script"


    #  - stage: Unit Tests
    #    before_install: echo "Unit Tests Before install"
    #    install: echo "Unit tests install"
    #    script: echo "Unit Tests stage"
    #  - stage: Integration Test
    #    script: echo "Deploying to GitHub releases ..."

    #osx_image: xcode9.3



    #script:
  #- echo "TRAVIS_OS_NAME = ${TRAVIS_OS_NAME}"
#- mvn package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true